version: '4.36.0'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "/c/Users/Pc/Downloads/Prometheus_Grafana:/etc/prometheus"

    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
